-- Mirrors the schema of the original deployment (schema-only dump, 2026-09-30).
-- Every statement is idempotent so this is a no-op on an existing database.

create table if not exists users (
	id bigint generated by default as identity primary key,
	tg_token text,
	access_token text,
	grabbers json default '[]'::json,
	name text not null default '',
	additional text not null default ''
);

create table if not exists pool (
	id bigint generated by default as identity,
	"user" bigint,
	message json,
	failed boolean not null default false,
	approved boolean,
	constraint pool_duplicate_pkey primary key (id)
);
create index if not exists pool_user_approved_idx on pool ("user", approved);

create table if not exists published_logs (
	post_id bigint not null,
	target text not null,
	constraint published_logs_pkey primary key (post_id, target),
	constraint published_logs_post_id_fkey foreign key (post_id) references pool(id)
);
